#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    // Read the mutated input file generated by the fuzzer
    FILE *f = fopen(".cur_input", "rb");
    if (!f) return 0;
    
    char buf[8] = {0};
    fread(buf, 1, 4, f);
    fclose(f);

    // VULNERABILITY: Trigger a crash if the first byte is mutated to 'F'.
    // This is a simplified condition to quickly verify the mutation engine.
    if (buf[0] == 'F') {
        char *crash = NULL;
        *crash = 1; // Intentional null pointer dereference (SIGSEGV)
    }

    return 0;
}